ASFLAGS_ADDITIONAL = -march=armv7-a -mfloat-abi=hard -mfpu=neon
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/MATLAB/SUPPOR~1/R2016a/toolbox/target/SUPPOR~1/BEAGLE~1/registry/..
STACK_SIZE = 64
