function CodeDefine() { 
this.def = new Array();
this.def["runModel"] = {file: "ert_main_c.html",line:36,type:"var"};
this.def["stopSem"] = {file: "ert_main_c.html",line:37,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_c.html",line:38,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_c.html",line:39,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_c.html",line:40,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_c.html",line:41,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_c.html",line:42,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_c.html",line:43,type:"fcn"};
this.def["exitTask"] = {file: "ert_main_c.html",line:60,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_c.html",line:65,type:"fcn"};
this.def["main"] = {file: "ert_main_c.html",line:83,type:"fcn"};
this.def["ADC_B"] = {file: "ADC_c.html",line:26,type:"var"};
this.def["ADC_X"] = {file: "ADC_c.html",line:29,type:"var"};
this.def["ADC_DW"] = {file: "ADC_c.html",line:32,type:"var"};
this.def["ADC_U"] = {file: "ADC_c.html",line:35,type:"var"};
this.def["ADC_Y"] = {file: "ADC_c.html",line:38,type:"var"};
this.def["ADC_M_"] = {file: "ADC_c.html",line:41,type:"var"};
this.def["ADC_M"] = {file: "ADC_c.html",line:42,type:"var"};
this.def["rt_ertODEUpdateContinuousStates"] = {file: "ADC_c.html",line:57,type:"fcn"};
this.def["ADC_norm"] = {file: "ADC_c.html",line:124,type:"fcn"};
this.def["ADC_norm_l"] = {file: "ADC_c.html",line:164,type:"fcn"};
this.def["rt_powd_snf"] = {file: "ADC_c.html",line:203,type:"fcn"};
this.def["rt_roundd_snf"] = {file: "ADC_c.html",line:249,type:"fcn"};
this.def["rt_remd_snf"] = {file: "ADC_c.html",line:267,type:"fcn"};
this.def["ADC_sind"] = {file: "ADC_c.html",line:297,type:"fcn"};
this.def["ADC_cosd"] = {file: "ADC_c.html",line:351,type:"fcn"};
this.def["ADC_norm_j"] = {file: "ADC_c.html",line:403,type:"fcn"};
this.def["ADC_norm_lw"] = {file: "ADC_c.html",line:443,type:"fcn"};
this.def["ADC_norm_p"] = {file: "ADC_c.html",line:483,type:"fcn"};
this.def["ADC_step"] = {file: "ADC_c.html",line:523,type:"fcn"};
this.def["ADC_derivatives"] = {file: "ADC_c.html",line:1899,type:"fcn"};
this.def["ADC_initialize"] = {file: "ADC_c.html",line:1914,type:"fcn"};
this.def["ADC_terminate"] = {file: "ADC_c.html",line:2051,type:"fcn"};
this.def["B_ADC_T"] = {file: "ADC_h.html",line:216,type:"type"};
this.def["DW_ADC_T"] = {file: "ADC_h.html",line:228,type:"type"};
this.def["X_ADC_T"] = {file: "ADC_h.html",line:233,type:"type"};
this.def["XDot_ADC_T"] = {file: "ADC_h.html",line:238,type:"type"};
this.def["XDis_ADC_T"] = {file: "ADC_h.html",line:243,type:"type"};
this.def["ODE4_IntgData"] = {file: "ADC_h.html",line:252,type:"type"};
this.def["ExtU_ADC_T"] = {file: "ADC_h.html",line:265,type:"type"};
this.def["ExtY_ADC_T"] = {file: "ADC_h.html",line:272,type:"type"};
this.def["P_ADC_T"] = {file: "ADC_types_h.html",line:27,type:"type"};
this.def["RT_MODEL_ADC_T"] = {file: "ADC_types_h.html",line:30,type:"type"};
this.def["ADC_P"] = {file: "ADC_data_c.html",line:26,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:33,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:57,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:68,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:92,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:33,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:57,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:31,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:32,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:33,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:34,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:35,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:36,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:42,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:54,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:60,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:66,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:72,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:43,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:50,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:57,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:97,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:104,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:111,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:118,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:125,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:132,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:139,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:146,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:153,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:174,type:"type"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["ADC_c.html"] = "../ADC.c";
	this.html2Root["ADC_c.html"] = "ADC_c.html";
	this.html2SrcPath["ADC_h.html"] = "../ADC.h";
	this.html2Root["ADC_h.html"] = "ADC_h.html";
	this.html2SrcPath["ADC_private_h.html"] = "../ADC_private.h";
	this.html2Root["ADC_private_h.html"] = "ADC_private_h.html";
	this.html2SrcPath["ADC_types_h.html"] = "../ADC_types.h";
	this.html2Root["ADC_types_h.html"] = "ADC_types_h.html";
	this.html2SrcPath["ADC_data_c.html"] = "../ADC_data.c";
	this.html2Root["ADC_data_c.html"] = "ADC_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","ADC_c.html","ADC_h.html","ADC_private_h.html","ADC_types_h.html","ADC_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html"];
